[package]
name = "clipboard_listener"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
#  https://github.com/ChurchTao/clipboard-rs/blob/HEAD/README_ZH.md
clipboard-rs = "0.2.0"
enigo = "0.2.1"
# https://github.com/miniben-90/x-win/blob/main/x-win-rs/examples/get_window_icon.rs
x-win = "1.10.2"
serde_json = "1.0.127"


[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
