// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class IconsClient {
  final Uint8List data;
  final IconsConfig config;

  const IconsClient({
    required this.data,
    required this.config,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<IconsClient> newInstance(
          {required List<int> data, required IconsConfig config}) =>
      RustLib.instance.api
          .crateApiIconsIconsClientNew(data: data, config: config);

  Future<void> toAndroid() =>
      RustLib.instance.api.crateApiIconsIconsClientToAndroid(
        that: this,
      );

  Future<void> toCustom() =>
      RustLib.instance.api.crateApiIconsIconsClientToCustom(
        that: this,
      );

  Future<void> toIos() => RustLib.instance.api.crateApiIconsIconsClientToIos(
        that: this,
      );

  Future<void> toMacos() =>
      RustLib.instance.api.crateApiIconsIconsClientToMacos(
        that: this,
      );

  Future<void> toOhos() => RustLib.instance.api.crateApiIconsIconsClientToOhos(
        that: this,
      );

  Future<void> toWeb() => RustLib.instance.api.crateApiIconsIconsClientToWeb(
        that: this,
      );

  Future<void> toWindows() =>
      RustLib.instance.api.crateApiIconsIconsClientToWindows(
        that: this,
      );

  @override
  int get hashCode => data.hashCode ^ config.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconsClient &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          config == other.config;
}

class IconsConfig {
  final bool android;
  final bool ios;
  final bool ohos;
  final bool macos;
  final bool windows;
  final bool web;
  final Uint32List custom;

  const IconsConfig({
    required this.android,
    required this.ios,
    required this.ohos,
    required this.macos,
    required this.windows,
    required this.web,
    required this.custom,
  });

  @override
  int get hashCode =>
      android.hashCode ^
      ios.hashCode ^
      ohos.hashCode ^
      macos.hashCode ^
      windows.hashCode ^
      web.hashCode ^
      custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconsConfig &&
          runtimeType == other.runtimeType &&
          android == other.android &&
          ios == other.ios &&
          ohos == other.ohos &&
          macos == other.macos &&
          windows == other.windows &&
          web == other.web &&
          custom == other.custom;
}
