// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compress`, `png_2_jpeg`

enum ImageFormat {
  /// An Image in PNG Format
  png,

  /// An Image in JPEG Format
  jpeg,

  /// An Image in GIF Format
  gif,

  /// An Image in WEBP Format
  webP,

  /// An Image in general PNM Format
  pnm,

  /// An Image in TIFF Format
  tiff,

  /// An Image in TGA Format
  tga,

  /// An Image in DDS Format
  dds,

  /// An Image in BMP Format
  bmp,

  /// An Image in ICO Format
  ico,

  /// An Image in Radiance HDR Format
  hdr,

  /// An Image in OpenEXR Format
  openExr,

  /// An Image in farbfeld Format
  farbfeld,

  /// An Image in AVIF Format
  avif,

  /// An Image in QOI Format
  qoi,

  /// An Image in PCX Format
  pcx,
  ;
}

class TinyClient {
  final String path;
  final String output;

  const TinyClient({
    required this.path,
    required this.output,
  });

  Future<ImageFormat?> fileType() =>
      RustLib.instance.api.crateApiTinyPngTinyClientFileType(
        that: this,
      );

  static Future<TinyClient> fromPath({required String path, String? output}) =>
      RustLib.instance.api
          .crateApiTinyPngTinyClientFromPath(path: path, output: output);

  Future<String> img2Webp({required int quality}) => RustLib.instance.api
      .crateApiTinyPngTinyClientImg2Webp(that: this, quality: quality);

  Future<String> imgConvert(
          {required ImageFormat target, int? quality, int? size}) =>
      RustLib.instance.api.crateApiTinyPngTinyClientImgConvert(
          that: this, target: target, quality: quality, size: size);

  Future<bool> isImageFile({required String path}) => RustLib.instance.api
      .crateApiTinyPngTinyClientIsImageFile(that: this, path: path);

  Future<String> jpeg2Png({int? quality}) => RustLib.instance.api
      .crateApiTinyPngTinyClientJpeg2Png(that: this, quality: quality);

  Future<String> parse({required int quality}) => RustLib.instance.api
      .crateApiTinyPngTinyClientParse(that: this, quality: quality);

  Future<String> thumbnail({required int width, required int height}) =>
      RustLib.instance.api.crateApiTinyPngTinyClientThumbnail(
          that: this, width: width, height: height);

  @override
  int get hashCode => path.hashCode ^ output.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TinyClient &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          output == other.output;
}
