// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dump_windows`, `get_browser_info`, `get_location_from_view`

Future<void> getSelectFile() =>
    RustLib.instance.api.crateApiWindowsGetSelectFile();

Future<void> getCurrentPath() =>
    RustLib.instance.api.crateApiWindowsGetCurrentPath();
