// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'entities.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<NetWorkEntity> getNetworks() =>
    RustLib.instance.api.crateApiSystemInfoGetNetworks();

List<ProcessEntity> getProcesses() =>
    RustLib.instance.api.crateApiSystemInfoGetProcesses();

String? findPid({required String name}) =>
    RustLib.instance.api.crateApiSystemInfoFindPid(name: name);

List<CpuEntity> getCpus() => RustLib.instance.api.crateApiSystemInfoGetCpus();
