// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/active_window/window.dart';
import 'api/application.dart';
import 'api/keypress_simulator/simulator.dart';
import 'api/system_clipboard/clipboard.dart';
import 'api/system_info/cpus.dart';
import 'api/system_info/entity.dart';
import 'api/system_info/networks.dart';
import 'api/system_info/process.dart';
import 'api/system_info/system_info.dart';
import 'api/system_tray/entity.dart';
import 'api/tiny_png/tiny_png.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ManagerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SenderStringPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Manager
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          dynamic raw);

  @protected
  SenderString
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          dynamic raw);

  @protected
  FutureOr<String> Function(String)
      dco_decode_DartFn_Inputs_String_Output_String_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String?> dco_decode_Map_String_opt_String(dynamic raw);

  @protected
  Map<String, BigInt> dco_decode_Map_String_u_64(dynamic raw);

  @protected
  Manager
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          dynamic raw);

  @protected
  SenderString
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ClipboardData dco_decode_box_autoadd_clipboard_data(dynamic raw);

  @protected
  CPImage dco_decode_box_autoadd_cp_image(dynamic raw);

  @protected
  FFIIconEvent dco_decode_box_autoadd_ffi_icon_event(dynamic raw);

  @protected
  FFIPhysicalPosition dco_decode_box_autoadd_ffi_physical_position(dynamic raw);

  @protected
  FFIRect dco_decode_box_autoadd_ffi_rect(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ClipboardData dco_decode_clipboard_data(dynamic raw);

  @protected
  CPImage dco_decode_cp_image(dynamic raw);

  @protected
  CpuEntity dco_decode_cpu_entity(dynamic raw);

  @protected
  CpuUsageEntity dco_decode_cpu_usage_entity(dynamic raw);

  @protected
  DataType dco_decode_data_type(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FFIIconEvent dco_decode_ffi_icon_event(dynamic raw);

  @protected
  FFIMouseButton dco_decode_ffi_mouse_button(dynamic raw);

  @protected
  FFIMouseButtonState dco_decode_ffi_mouse_button_state(dynamic raw);

  @protected
  FFIPhysicalPosition dco_decode_ffi_physical_position(dynamic raw);

  @protected
  FFIPhysicalSize dco_decode_ffi_physical_size(dynamic raw);

  @protected
  FFIRect dco_decode_ffi_rect(dynamic raw);

  @protected
  FFISysTrayEvent dco_decode_ffi_sys_tray_event(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IconEntity dco_decode_icon_entity(dynamic raw);

  @protected
  InfoEntity dco_decode_info_entity(dynamic raw);

  @protected
  IpNetworkEntity dco_decode_ip_network_entity(dynamic raw);

  @protected
  IpNetworkType dco_decode_ip_network_type(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CpuEntity> dco_decode_list_cpu_entity(dynamic raw);

  @protected
  List<IpNetworkEntity> dco_decode_list_ip_network_entity(dynamic raw);

  @protected
  List<NetWorkEntity> dco_decode_list_net_work_entity(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProcessEntity> dco_decode_list_process_entity(dynamic raw);

  @protected
  List<(String, String?)> dco_decode_list_record_string_opt_string(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  List<WindowIconEntity> dco_decode_list_window_icon_entity(dynamic raw);

  @protected
  MySysTrayEventEnum dco_decode_my_sys_tray_event_enum(dynamic raw);

  @protected
  NetWorkEntity dco_decode_net_work_entity(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CPImage? dco_decode_opt_box_autoadd_cp_image(dynamic raw);

  @protected
  FFIIconEvent? dco_decode_opt_box_autoadd_ffi_icon_event(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PositionEntity dco_decode_position_entity(dynamic raw);

  @protected
  ProcessEntity dco_decode_process_entity(dynamic raw);

  @protected
  ProcessStatusEntity dco_decode_process_status_entity(dynamic raw);

  @protected
  (Map<String, BigInt>, Map<String, String?>)
      dco_decode_record_map_string_u_64_map_string_opt_string(dynamic raw);

  @protected
  (String, String?) dco_decode_record_string_opt_string(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UsageEntity dco_decode_usage_entity(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WindowEntity dco_decode_window_entity(dynamic raw);

  @protected
  WindowIconEntity dco_decode_window_icon_entity(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Manager
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          SseDeserializer deserializer);

  @protected
  SenderString
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String?> sse_decode_Map_String_opt_String(
      SseDeserializer deserializer);

  @protected
  Map<String, BigInt> sse_decode_Map_String_u_64(SseDeserializer deserializer);

  @protected
  Manager
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          SseDeserializer deserializer);

  @protected
  SenderString
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ClipboardData sse_decode_box_autoadd_clipboard_data(
      SseDeserializer deserializer);

  @protected
  CPImage sse_decode_box_autoadd_cp_image(SseDeserializer deserializer);

  @protected
  FFIIconEvent sse_decode_box_autoadd_ffi_icon_event(
      SseDeserializer deserializer);

  @protected
  FFIPhysicalPosition sse_decode_box_autoadd_ffi_physical_position(
      SseDeserializer deserializer);

  @protected
  FFIRect sse_decode_box_autoadd_ffi_rect(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ClipboardData sse_decode_clipboard_data(SseDeserializer deserializer);

  @protected
  CPImage sse_decode_cp_image(SseDeserializer deserializer);

  @protected
  CpuEntity sse_decode_cpu_entity(SseDeserializer deserializer);

  @protected
  CpuUsageEntity sse_decode_cpu_usage_entity(SseDeserializer deserializer);

  @protected
  DataType sse_decode_data_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FFIIconEvent sse_decode_ffi_icon_event(SseDeserializer deserializer);

  @protected
  FFIMouseButton sse_decode_ffi_mouse_button(SseDeserializer deserializer);

  @protected
  FFIMouseButtonState sse_decode_ffi_mouse_button_state(
      SseDeserializer deserializer);

  @protected
  FFIPhysicalPosition sse_decode_ffi_physical_position(
      SseDeserializer deserializer);

  @protected
  FFIPhysicalSize sse_decode_ffi_physical_size(SseDeserializer deserializer);

  @protected
  FFIRect sse_decode_ffi_rect(SseDeserializer deserializer);

  @protected
  FFISysTrayEvent sse_decode_ffi_sys_tray_event(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IconEntity sse_decode_icon_entity(SseDeserializer deserializer);

  @protected
  InfoEntity sse_decode_info_entity(SseDeserializer deserializer);

  @protected
  IpNetworkEntity sse_decode_ip_network_entity(SseDeserializer deserializer);

  @protected
  IpNetworkType sse_decode_ip_network_type(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CpuEntity> sse_decode_list_cpu_entity(SseDeserializer deserializer);

  @protected
  List<IpNetworkEntity> sse_decode_list_ip_network_entity(
      SseDeserializer deserializer);

  @protected
  List<NetWorkEntity> sse_decode_list_net_work_entity(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProcessEntity> sse_decode_list_process_entity(
      SseDeserializer deserializer);

  @protected
  List<(String, String?)> sse_decode_list_record_string_opt_string(
      SseDeserializer deserializer);

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
      SseDeserializer deserializer);

  @protected
  List<WindowIconEntity> sse_decode_list_window_icon_entity(
      SseDeserializer deserializer);

  @protected
  MySysTrayEventEnum sse_decode_my_sys_tray_event_enum(
      SseDeserializer deserializer);

  @protected
  NetWorkEntity sse_decode_net_work_entity(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CPImage? sse_decode_opt_box_autoadd_cp_image(SseDeserializer deserializer);

  @protected
  FFIIconEvent? sse_decode_opt_box_autoadd_ffi_icon_event(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PositionEntity sse_decode_position_entity(SseDeserializer deserializer);

  @protected
  ProcessEntity sse_decode_process_entity(SseDeserializer deserializer);

  @protected
  ProcessStatusEntity sse_decode_process_status_entity(
      SseDeserializer deserializer);

  @protected
  (Map<String, BigInt>, Map<String, String?>)
      sse_decode_record_map_string_u_64_map_string_opt_string(
          SseDeserializer deserializer);

  @protected
  (String, String?) sse_decode_record_string_opt_string(
      SseDeserializer deserializer);

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UsageEntity sse_decode_usage_entity(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WindowEntity sse_decode_window_entity(SseDeserializer deserializer);

  @protected
  WindowIconEntity sse_decode_window_icon_entity(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          Manager self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          SenderString self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_String_Output_String_AnyhowException(
      FutureOr<String> Function(String) self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_opt_String(
      Map<String, String?> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_u_64(
      Map<String, BigInt> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          Manager self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          SenderString self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_clipboard_data(
      ClipboardData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cp_image(CPImage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_icon_event(
      FFIIconEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_physical_position(
      FFIPhysicalPosition self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_rect(FFIRect self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_clipboard_data(ClipboardData self, SseSerializer serializer);

  @protected
  void sse_encode_cp_image(CPImage self, SseSerializer serializer);

  @protected
  void sse_encode_cpu_entity(CpuEntity self, SseSerializer serializer);

  @protected
  void sse_encode_cpu_usage_entity(
      CpuUsageEntity self, SseSerializer serializer);

  @protected
  void sse_encode_data_type(DataType self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_icon_event(FFIIconEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_mouse_button(
      FFIMouseButton self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_mouse_button_state(
      FFIMouseButtonState self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_physical_position(
      FFIPhysicalPosition self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_physical_size(
      FFIPhysicalSize self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_rect(FFIRect self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_sys_tray_event(
      FFISysTrayEvent self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_icon_entity(IconEntity self, SseSerializer serializer);

  @protected
  void sse_encode_info_entity(InfoEntity self, SseSerializer serializer);

  @protected
  void sse_encode_ip_network_entity(
      IpNetworkEntity self, SseSerializer serializer);

  @protected
  void sse_encode_ip_network_type(IpNetworkType self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cpu_entity(
      List<CpuEntity> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ip_network_entity(
      List<IpNetworkEntity> self, SseSerializer serializer);

  @protected
  void sse_encode_list_net_work_entity(
      List<NetWorkEntity> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_entity(
      List<ProcessEntity> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_opt_string(
      List<(String, String?)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_u_64(
      List<(String, BigInt)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_window_icon_entity(
      List<WindowIconEntity> self, SseSerializer serializer);

  @protected
  void sse_encode_my_sys_tray_event_enum(
      MySysTrayEventEnum self, SseSerializer serializer);

  @protected
  void sse_encode_net_work_entity(NetWorkEntity self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cp_image(
      CPImage? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_icon_event(
      FFIIconEvent? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_position_entity(
      PositionEntity self, SseSerializer serializer);

  @protected
  void sse_encode_process_entity(ProcessEntity self, SseSerializer serializer);

  @protected
  void sse_encode_process_status_entity(
      ProcessStatusEntity self, SseSerializer serializer);

  @protected
  void sse_encode_record_map_string_u_64_map_string_opt_string(
      (Map<String, BigInt>, Map<String, String?>) self,
      SseSerializer serializer);

  @protected
  void sse_encode_record_string_opt_string(
      (String, String?) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_u_64(
      (String, BigInt) self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usage_entity(UsageEntity self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_window_entity(WindowEntity self, SseSerializer serializer);

  @protected
  void sse_encode_window_icon_entity(
      WindowIconEntity self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManager(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderString(
          int ptr);
}
