// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Configuration data for Pico.
class Config {
  /// The paths to the PNG input files and directories.
  final List<String> inputPaths;

  /// The path to the ICO output file.
  final String outputPath;

  /// Whether to sort ICO entries by descending resolution.
  final bool sort;

  /// Whether to overwrite an existing ICO output file.
  final bool force;

  const Config({
    required this.inputPaths,
    required this.outputPath,
    required this.sort,
    required this.force,
  });

  @override
  int get hashCode =>
      inputPaths.hashCode ^
      outputPath.hashCode ^
      sort.hashCode ^
      force.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          inputPaths == other.inputPaths &&
          outputPath == other.outputPath &&
          sort == other.sort &&
          force == other.force;
}
