name: clipboard_listener
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/iakii/flutter_plugins/packages/clipboard_listener
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_lib_core:
    git:
      url: https://github.com/iakii/flutter_plugins.git
      path: packages/flutter_rust_lib_core
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
