name: bindgo
description: Use Dart to call Shell, complete the work of compiling Golang CGO code into a so, dll, a, WASM, and etc. And place it in the corresponding source file directory of each Flutter platform.
version: 0.2.0
homepage: https://github.com/ggdream/bindgo

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  path: ^1.9.0
  process_run: ^1.2.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.18.2
