[package]
name = "rust_ffi_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
enigo = "0.2.1"
flutter_rust_bridge = "=2.3.0"
sysinfo = "0.31.3"


[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
