import 'dart:convert';
import 'dart:io';

main() {
  v2();
}

v2() {
  const path = './bootstrap-icons.json';

  File file = File(path);
  if (file.existsSync()) {
    final content = file.readAsStringSync();
    String sb = '';

    jsonDecode(content).forEach((key, value) {
      // 十进制转16进制

      String iconName = key;
      final String unicode = (value as int).toRadixString(16);

      if (firtIsNumber(iconName)) {
        iconName = 'number-$iconName';
      }
      iconName = iconName.replaceAll('-', '_');

      sb += ('''
/// <i class="bi bi-$key"></i> &#x2014; [$key](https://icons.getbootstrap.com/icons/$key/)
  static const IconData $iconName = IconData(0x$unicode, fontFamily: 'BootstrapIcons',fontPackage: 'bootscrap_icons');
''');
    });

    final outFile = File('../lib/bootscrap_icons.dart');

    outFile.writeAsStringSync('''
// ignore_for_file: constant_identifier_names
import 'package:flutter/material.dart';
// This file is generated by a script, do not edit manually.\n\n
abstract final class BTIcons {
${sb.toString()}
}

''');
  }
}

firstUp(String text) {
  if (text.isEmpty) {
    return text;
  }
  return text[0].toUpperCase() + text.substring(1);
}

firstDown(String text) {
  if (text.isEmpty) {
    return text;
  }
  return text[0].toLowerCase() + text.substring(1);
}

// 首字符是数字
firtIsNumber(String text) {
  if (text.isEmpty) {
    return false;
  }
  return text[0].codeUnitAt(0) >= 48 && text[0].codeUnitAt(0) <= 57;
}
