[package]
name = "system_hotkey"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
serde = {version = "1.0", features = ["derive"], optional=true}
flutter_rust_bridge = "=2.4.0"
rdev = { git = "https://github.com/qzd1989/rdev.git", branch = "stop_listen" }



[profile.release]
opt-level = 'z'
lto = true
strip = true
codegen-units = 1
panic = 'abort'
