// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: prefer_const_constructors

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'entity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<ProcessEntity> getProcesses() =>
    RustLib.instance.api.crateApiSystemInfoProcessGetProcesses();

Future<String?> findPid({required String name}) =>
    RustLib.instance.api.crateApiSystemInfoProcessFindPid(name: name);

bool kill({required String name}) =>
    RustLib.instance.api.crateApiSystemInfoProcessKill(name: name);
