[package]
name = "flutter_rust_lib_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]


[dependencies]
flutter_rust_bridge = "=2.3.0"
# for system tray
tray-icon = "0.17.0"
winit = "0.29.15"

# for system infomation
sysinfo = "0.31.4"

# for 模拟按键
enigo = "0.2.1"

# for 监听剪贴板等操作
#  https://github.com/ChurchTao/clipboard-rs/blob/HEAD/README_ZH.md
clipboard-rs = "0.2.0"
# https://github.com/miniben-90/x-win/blob/main/x-win-rs/examples/get_window_icon.rs
x-win = "1.10.2"

# for tiny png 

oxipng = { version = "9.1.2", features = [
  "parallel",
  "zopfli",
  "filetime",
], default-features = false }
webp = "0.3.0"


# 公共库
image = "0.25.2"
serde_json = "1.0.127"
serde = { version = "1.0", features = ["derive"] }



[target."cfg(target_os = \"macos\")".dependencies]
core-foundation = "0.10"



[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

