// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'entity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `example`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AriaClient>>
abstract class AriaClient implements RustOpaqueInterface {
  Future<void> addUrl({required String url, TaskOptions? options});

  static Future<AriaClient> connect({required String url}) =>
      RustLib.instance.api.crateApiAria2ClientAriaClientConnect(url: url);

  Future<void> setGlobalOption({required TaskOptions option});
}
